# Generated by Django 5.2.17 on 2026-09-13 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Record Id')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(choices=[('ingreso', 'ingreso'), ('salida', 'salida')], default='ingreso', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
