# Generated by Django 5.2.17 on 2026-09-25 18:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.TimeField(default=datetime.time(9, 30))),
                ('exit_time', models.TimeField(default=datetime.time(17, 30))),
            ],
        ),
        migrations.AddField(
            model_name='assistancerecord',
            name='early_exit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReentryPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reentry_permits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
